import './globals.css'
import { Inter, Montserrat } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Sundra | Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={montserrat.className}>
      <body >{children}</body>
    </html>
  )
}
